timeout: '1200s'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'quote-linker-web', '--image', 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA'
