timeout: '1200s'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'quotelinkercom'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service=quotelinkercom'
      - '--domain=quotelinker.com'
      - '--region=us-central1'
      - '--force-override'
images:
  - 'gcr.io/$PROJECT_ID/quote-linker-web:$COMMIT_SHA'
