name: Lighthouse CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build and Start Next.js
        run: npm run build && npm start &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --upload.target=temporary-public-storage
