name: Lighthouse CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build, serve, wait & run Lighthouse CI
        run: |
          npm run build
          npm run start &                            # Start Next.js server (runs on port 3000 from server.js)
          npx wait-on http://localhost:3000 --timeout 60s
          npx lhci autorun --upload.target=temporary-public-storage
